build:
  nodes:
      validation:
          tests:
              override:
              - php-scrutinizer-run --enable-security-analysis
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
