checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
tools:
    php_code_coverage: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
filter:
    excluded_paths: [tests, vendor]
build:
    environment:
        php:
            version: 5.6
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
